### ISSUE TITLE
ToDo list and general discussion 

### ISSUE THREAD

**Issue by aGotelli** [aGotelli/Projet1#12]
Hi, 
As I have a couple of hours to kill in the airport I start to write down some things about this little project we want to enjoy. 

The following are some ideas I had at the end of June.

- [x] Check portability to ROS Noetic. I have it in Windows but I have to figured out how to use it first, so probably that would be the task of someone who already has it on Ubuntu.

- [ ] Work on portability on ROS 2 (for that I will install it quite soon) 

- [ ] Improving existing documentation and develop an API in Doxygen. A documentation is already present in the README. Now the newby for this project can take a read of it and give us a feedback of the part that are not clear or missing. The idea is to remove the README and just provide a very good API. 

- [ ] Make the project depending on a inner library. Meaning that, the source file that are not to be modified should be hidden in a separate library the project depends on. 

- [ ] Remove the bottleneck in the sensors related topic in order to use an undermined amount of them. The code can manage an arbitrary number of sensors. However, the topic used to exchange the states holds only two sensors. This should be changed.

- [ ] Reorganization of the Python script in a more professional layout. For the moment it's just something which does it's job, but I know it can be improved. Maybe some plots could be added.

- [ ] Change the overall project layout. Instead of defining a class in the project code, but using plugin lib.

- [ ] Add a general solver which parses an URDF and computes the matrices for the kinematic model.

- [ ] Add some other models of mobile robots

- [ ] Reduce memory leaks (already kind of done but still not completed). Rviz does not free up memory while working and this is such annoying. Maybe move it into Gazebo.

- [ ] (If Gazebo) It would be nice to start including some dynamic

- [ ] Create an application to run the estimator with the simulation.

- [ ] Add some controller for trajectory tracking. I have a static feedback already done and a Lyapunov with some bug. I didn't have the time to complete them as I did them in the semester. Later, if you consider it a good idea, we can add them to the project. 

These lists shows the things to do in a pseudo order of importance. But we can do as we want. 
You can download the repository from master or andrea, they should be the same. 
However you should not push to master neither my branch. The best thing is to clone the master on your computer and then change the branch name. Then pushing the content will create a new branch. This is mostly because Bianca has the repository link in her LinkedIn, it would be nice to leave it always working. Once we have something, we'll merge the repositories.

We can discuss about general topics here, everyone can share code and questions. For questions and problem to a specific point, feel free to open new issues. 

Working in different branches could also provide different solutions for the same problem, that is always interesting. 

If everyone has any proposal, idea or doubts it would be nice to have a common chat here 😁😁

**Comment by aGotelli** [comment]
@blento @enhatem @DevasmitoDas @marcodemutti 

Seems like we need to tag each other in the text to see notifications

**Comment by DevasmitoDas** [comment]
Doxygen seems to be interesting.

**Comment by aGotelli** [comment]
Yes ! A lot! It is widely used and super simple to implement. That's way a want to get used. 

For example, all the ROS documentation is provided in Doxygen!

Once installed Doxygen on your computer:
           sudo apt-get update -y
           sudo apt-get install -y doxygen

It is super simple. It generates the documentation from the comments in the code! Plus you can add images ans stuffs. The file is generated as an .html. on virtually, you can use an editor to open it. In practice it's more convenient to use Firefox.

**Comment by DevasmitoDas** [comment]
That seems to be quite GUI based. Cool. I will install it.

**Comment by DevasmitoDas** [comment]
What do you mean by <<reorganization of the python script>>?

**Comment by DevasmitoDas** [comment]
Réorganisation of python script?

**Comment by aGotelli** [comment]
> Réorganisation of python script?

I mean that, so far, it's something like 400 lines of code which me and Bianca just tried to organise with some sense. Now it can be really improved following a more general object oriented programming. I have putted in the to do list because I want to do it just to understand more python. Because for the moment I can only do the very basic

**Comment by DevasmitoDas** [comment]
Ah ! Okay. I understand. If you want to learn python clearly, I would like to suggest you to do some programming on deep learning. It's quite helpful. But this is out of the context of this discussion here.
